[workspace]

members = [
    "crates/*",
    "drivers/*",
]

exclude = [
    "crates/pi-benchmarks",
    "drivers/klipper-code-gen",
]

[profile.release]
# opt-level = "z"
lto = true
# Enabling debugging symbols for perf.
# See: https://cesarvr.io/post/rust-performance/
debug=true
