export config from './config/reducers/configReducer'
export pluginManager from './pluginManager/reducers/pluginManagerReducer'
export jobQueue from './jobQueue/reducers/jobQueueReducer'
export log from './log/reducers/logReducer'
export spool from './spool/reducers/spoolReducer'
export status from './printer/reducers/statusReducer'
