#!/bin/bash
set -e
cd "$( dirname "${BASH_SOURCE[0]}" )"

# Using taskset to reserve CPU #0 for print drivers such as teg-marlin
# Note: This will not work on single cored servers. Generally teg is only intended to be used
# on multi-core devices.
taskset --cpu-list 1-1024 ./webrtc-streamer -H 127.0.0.1:8009
