#!/bin/bash
set -e
cd "$( dirname "${BASH_SOURCE[0]}" )" && cd ../

if [ -z "$SKIP_BUILD" ]
then
  mkdir -p ./snapcraft/dist
  rm -f ./snapcraft/dist/*.snap

  if [ "$SKIP_CLEAN" == "1" ]
  then
    echo "Skipping clean!"
  fi

  if [ -z "$TEG_DEBUG_BUILD" ]
  then
    TEG_BUILD_PROFILE=release
  else
    TEG_BUILD_PROFILE=debug
  fi

  if [ "$TEG_BUILD_PROFILE" == "release" ]
  then
    TEG_BUILD_PROFILE_ARG=--release
  fi

  if [ "$TEG_BUILD_PROFILE" == "release" ]
  then
    TEG_TARGET_DIR_X64=./target/release
    TEG_TARGET_DIR_ARMV7=./target/armv7-unknown-linux-gnueabihf/release/
  else
    TEG_TARGET_DIR_X64=./target/debug
    TEG_TARGET_DIR_ARMV7=./target/armv7-unknown-linux-gnueabihf/debug/
  fi

  if [ -z "$SKIP_RUST" ]
  then
    if [ -z "$SKIP_X64" ]
    then
      echo "Building rust binaries for X64 in $TEG_BUILD_PROFILE..."
      rm -rf ./snapcraft/x64/bin
      mkdir -p ./snapcraft/x64/bin

      cp -R ./crates/server/migrations ./snapcraft/x64/bin/migrations

      cargo build --workspace ${TEG_BUILD_PROFILE_ARG}

      cp ${TEG_TARGET_DIR_X64}/teg-invite ./snapcraft/x64/bin/teg-invite
      cp ${TEG_TARGET_DIR_X64}/teg-marlin ./snapcraft/x64/bin/teg-marlin
      cp ${TEG_TARGET_DIR_X64}/teg-server ./snapcraft/x64/bin/teg-server
      cp ${TEG_TARGET_DIR_X64}/teg-health-monitor ./snapcraft/x64/bin/teg-health-monitor
      cp ./snapcraft/webrtc-server ./snapcraft/x64/bin/webrtc-server

      echo "Building rust binaries for X64 in $TEG_BUILD_PROFILE... [DONE]"
    else
      echo "Skipping x64!"
    fi

    if [ -z "$SKIP_ARMV7" ]
    then
      echo "Building rust binaries for Arm in $TEG_BUILD_PROFILE..."
      rm -rf ./snapcraft/armv7/bin
      mkdir -p ./snapcraft/armv7/bin

      cp -R ./crates/server/migrations ./snapcraft/armv7/bin/migrations

      cargo build --workspace ${TEG_BUILD_PROFILE_ARG} --target=armv7-unknown-linux-gnueabihf

      cp ${TEG_TARGET_DIR_ARMV7}/teg-invite ./snapcraft/armv7/bin/teg-invite
      cp ${TEG_TARGET_DIR_ARMV7}/teg-marlin ./snapcraft/armv7/bin/teg-marlin
      cp ${TEG_TARGET_DIR_ARMV7}/teg-server ./snapcraft/armv7/bin/teg-server
      cp ${TEG_TARGET_DIR_ARMV7}/teg-health-monitor ./snapcraft/armv7/bin/teg-health-monitor
      cp ./snapcraft/webrtc-server ./snapcraft/armv7/bin/webrtc-server

      echo "Building rust binaries for Arm in $TEG_BUILD_PROFILE... [DONE]"
    else
      echo "Skipping Arm!"
    fi
  else
    echo "\$SKIP_RUST: Reusing previous rust builds. Rust changes will *not* be included in this build."
  fi

  # TEG_VERSION=`node -e "console.log(require('./lerna.json').version);"`;
  if [ -z "$SKIP_SNAPCRAFT" ]
  then
    # sed -i -E "s/^version:[^\n]+/version: $TEG_VERSION/g" ./snapcraft.yaml
    if [ -z "$SKIP_X64" ]
    then
      echo "Building snap for X64 in $TEG_BUILD_PROFILE..."
      pushd .
      cd ./snapcraft/x64

      if [ -z "$SKIP_CLEAN" ]
      then
        snapcraft clean
        # snapcraft clean tegh
      fi

      if [ -z "$CI" ]
      then
        # Non CI
        snapcraft snap --debug
      else
        # CI
        sg lxd -c 'snapcraft snap --debug --use-lxd'
      fi

      mv ./*.snap ../dist/
      popd
      echo "Building snap for X64 in $TEG_BUILD_PROFILE... [DONE]"
    fi

    if [ -z "$SKIP_ARMV7" ]
    then
      echo "Building snap for Arm in $TEG_BUILD_PROFILE..."
      pushd .
      cd ./snapcraft/armv7

      if [ -z "$SKIP_CLEAN" ]
      then
        snapcraft clean
        # snapcraft clean tegh
      fi

      if [ -z "$CI" ]
      then
        # Non CI
        snapcraft snap --debug
      else
        # CI
        sg lxd -c 'snapcraft snap --debug --use-lxd'
      fi

      mv ./*.snap ../dist/
      popd
      echo "Building snap for Arm in $TEG_BUILD_PROFILE... [DONE]"
    fi

    # [ -z "$SKIP_ARMV7" ] && snapcraft snap --debug --target-arch armhf
    # [ -z "$SKIP_X64" ] && snapcraft snap --debug --target-arch amd64

    # snapcraft remote-build --launchpad-accept-public-upload
  fi
fi
