#!/bin/bash
set -e
# cd "$( dirname "${BASH_SOURCE[0]}" )" && cd ../

export DATABASE_URL=sqlite:`pwd`/db.sqlite

# Somehow adding and removing multilib installs something we need. It's weird but builds don't
# cross-compile without it.
sudo apt-get install gcc-multilib
sudo apt-get remove gcc-multilib
sudo snap install snapcraft --classic
sudo snap install multipass

sudo apt-get install \
  g++-arm-linux-gnueabihf

rustup target add armv7-unknown-linux-gnueabihf
cargo install sqlx-cli

# Database
pushd .
cd ./crates/server
sqlx db setup
popd

# Build
SKIP_CLEAN=1 SKIP_X64=1 ./scripts/build

# cd ./crates
# cargo build --workspace --target=armv7-unknown-linux-gnueabihf
