#!/bin/bash
set -e
# cd "$( dirname "${BASH_SOURCE[0]}" )" && cd ../

DATABASE_URL=sqlite:`pwd`/db.sqlite

# Somehow adding and removing multilib installs something we need. It's weird but builds don't
# cross-compile without it.
sudo apt-get install gcc-multilib
sudo apt-get remove gcc-multilib

sudo apt-get install \
  g++-arm-linux-gnueabihf

rustup target add armv7-unknown-linux-gnueabihf
cargo install sqlx-cli

cd ./crates/server

sqlx db setup

cargo build --target=armv7-unknown-linux-gnueabihf
