#!/bin/bash
set -e
cd "$( dirname "${BASH_SOURCE[0]}" )" && cd ../../

# Reset the artifact working directory
rm -rf artifact-working-dir
mkdir artifact-working-dir

# Copy services
cp -r ./services artifact-working-dir/services
# Copy binaries
mkdir -p artifact-working-dir/etc/

if [ "$PRINTSPOOL_ARCH" == "armv7l" ]
then
  cp ./target/armv7-unknown-linux-gnueabihf/*/printspool-* ./artifact-working-dir/etc/
elif [ "$PRINTSPOOL_ARCH" == "x86_64" ]
then
  cp ./target/*/printspool-* ./artifact-working-dir/etc/
else
  echo "Invalid PRINTSPOOL_ARCH: \"$PRINTSPOOL_ARCH\". Expected armv7l or x86_64"
  exit 1
fi

rm ./artifact-working-dir/etc/*.d
# Create .env
mkdir -p artifact-working-dir/etc
cp ./.env.production ./artifact-working-dir/etc/.env
cp -r ./crates/server/migrations ./artifact-working-dir/etc/
