#!/bin/bash
set -e

# USERNAME="root"
#
# if [ -z "$USERNAME" ]; then
#     echo "Username required."
#     exit 1
# fi

# add the user that runs the Tegh daemon (the snap's root user) to dialout
# so it can access the serial port.
sudo usermod -a -G dialout root

# newgrp -

# echo "$(id)"
# echo "$(groups root)"
# exit 1

# add a log directory for Tegh
sudo mkdir -p /run/log/tegh
sudo chmod 700 /run/log/tegh
sudo chown root: /run/log/tegh
