#!/bin/bash
set -e

# This is only needed for upgrading 0.14.0 closed beta users. Once 0.15 is fully deployed
# this can be removed because it is done for new users in the install hook.

PG_AUTHORIZED=1

psql -l >> /dev/null 2>&1 || export PG_AUTHORIZED=0

if [ "$PG_AUTHORIZED" == "0" ]
then
  echo "Setting up Postgres authorization"
  # Add the snap's root user to Postgres to give the daemon access to the database
  sudo -u postgres createuser -s root
  # Add a default database for the root user
  sudo createdb -O root root
  echo "Setting up Postgres authorization  [DONE]"
fi
