#!/bin/bash
set -e
cd "$( dirname "${BASH_SOURCE[0]}" )" && cd ../

rustup target add armv7-unknown-linux-gnueabihf

cargo install cargo-watch sqlx-cli

sudo mkdir /var/lib/teg-dev/
sudo chown `whoami`:`whoami` /var/lib/teg-dev/

# yarn
# yarn make-dirs

pushd
cd ./packages/teg-web-ui/
nvm install
nvm use
npm i -g yarn
yarn
popd

pushd
cd ./crages/server
sqlx database create
sqlx migrate run
popd
