#!/bin/bash
set -eE -o functrace

failure() {
  local lineno=$1
  local msg=$2
  echo "Failed at $lineno: $msg"
}
trap 'failure ${LINENO} "$BASH_COMMAND"' ERR

cd "$( dirname "${BASH_SOURCE[0]}" )" && cd ../

export NVM_DIR=$HOME/.nvm;
source $NVM_DIR/nvm.sh;

FRESH_INSTALL=0
if [[ -d "/usr/local/etc/printspool-dev/" ]]; then
    echo "Updating previous printspool dev environment, postgres database will not be reset"
else
    FRESH_INSTALL=1
fi

rustup target add armv7-unknown-linux-gnueabihf

cargo install cargo-watch sqlx-cli

sudo mkdir -p /var/local/printspool-dev/
sudo chown `whoami`:`whoami` /var/local/printspool-dev/

sudo mkdir -p /usr/local/etc/printspool-dev/common/
sudo chown -R `whoami`:`whoami` /usr/local/etc/printspool-dev/

if [[ FRESH_INSTALL == "1" ]]; then
  touch /usr/local/etc/printspool-dev/common/.is-fresh-install
fi

# Frontend
nvm install
nvm use
npm i -g yarn

pushd .
cd ./frontend/slicer-render/
wasm-pack build --target web --out-name web --out-dir ./pkg
popd

pushd .
cd ./frontend/teg-web-ui/
yarn
popd
