#!/bin/bash
set -e
cd "$( dirname "${BASH_SOURCE[0]}" )"

ARCH=$(uname -m)
FRESH_INSTALL=0
if [ -d "/usr/bin/teg" ]; then
    echo "Updating previous Teg for $ARCH install..."
else
    echo "Installing Teg for $ARCH..."
    FRESH_INSTALL=1
fi

# Install dependencies
sudo apt install \
  libgtk-3-0 \
  libasound2 \
  libbsd-dev \
  postgresql \
  postgresql-contrib \
  rsync

# create the user
# TEG_USER="teg"
# sudo useradd $TEG_USER || true
# sudo usermod -a -G dialout $TEG_USER || true

TEG_USER="root"

# create directories
sudo mkdir -p /etc/teg/
sudo mkdir -p /var/lib/teg/
sudo mkdir -p /var/lib/teg-common/

sudo chmod 700 /etc/teg/
sudo chmod 700 /var/lib/teg/
sudo chmod 700 /var/lib/teg-common/

sudo chown -R ${TEG_USER}:${TEG_USER} /etc/teg/
sudo chown -R ${TEG_USER}:${TEG_USER} /var/lib/teg/
sudo chown -R ${TEG_USER}:${TEG_USER} /var/lib/teg-common/


# create a tmp dir
SCRIPT_DIR=$(pwd)
WORK_DIR=$(mktemp -d)

# check if tmp dir was created
if [[ ! "$WORK_DIR" || ! -d "$WORK_DIR" ]]; then
  echo "Could not create temp dir"
  exit 1
fi

# deletes the temp directory
function cleanup {
  rm -rf "$WORK_DIR"
  echo "Deleted temp working directory $WORK_DIR"
}

# register the cleanup function to be called on the EXIT signal
trap cleanup EXIT

# Change to the tmp dir
cd $WORK_DIR

if [ "${LOCAL_ARTIFACT}" == "1" ]; then
  echo ""
  echo "Installing local development version of Teg"
  echo ""

  TEG_ARCH=$ARCH $SCRIPT_DIR/ci/create-artifact
  cp -r $SCRIPT_DIR/../artifact-working-dir/* ./
else
  # Download the latest release
  GITHUB_REPO="tegapp/teg"

  ARTIFACT_NAME="teg-$ARCH.zip"

  LATEST_RELEASE=$(curl -L -s -H 'Accept: application/json' https://github.com/$GITHUB_REPO/releases/latest)

  # The releases are returned in the format {"id":3622206,"tag_name":"hello-1.0.0.11",...},
  # we have to extract the tag_name.
  LATEST_VERSION=$(echo $LATEST_RELEASE | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')

  ARTIFACT_URL="https://github.com/$GITHUB_REPO/releases/download/$LATEST_VERSION/$ARTIFACT_NAME"

  wget $ARTIFACT_URL
  unzip $ARTIFACT_NAME
  rm $ARTIFACT_NAME
fi

# Download the latest webrtc-streamer release
GITHUB_REPO="mpromonet/webrtc-streamer"
LATEST_RELEASE=$(curl -L -s -H 'Accept: application/json' https://github.com/$GITHUB_REPO/releases/latest)

# The releases are returned in the format {"id":3622206,"tag_name":"hello-1.0.0.11",...},
# we have to extract the tag_name.
LATEST_VERSION=$(echo $LATEST_RELEASE | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')

ARTIFACT_DIR="webrtc-streamer-$LATEST_VERSION-Linux-$ARCH-Release"
ARTIFACT_NAME="$ARTIFACT_DIR.tar.gz"

ARTIFACT_URL="https://github.com/$GITHUB_REPO/releases/download/$LATEST_VERSION/$ARTIFACT_NAME"

wget $ARTIFACT_URL
tar -xf $ARTIFACT_NAME
rm $ARTIFACT_NAME
mv $ARTIFACT_DIR ./etc/webrtc-streamer

# Install etc (migrations, binaries, configs and webrtc-streamer)
sudo rsync --chown=$TEG_USER:$TEG_USER -a --delete ./etc/ /usr/local/etc/teg

# Install binaries on path
sudo ln -vsf "/usr/local/etc/teg/teg-invite" /usr/local/bin

# Install System D service files
sudo chmod 644 ./services/*
sudo mv ./services/* /lib/systemd/system/

systemctl daemon-reload
sudo systemctl restart teg-server teg-health-monitor teg-webrtc-streamer
sudo systemctl enable teg-server teg-health-monitor teg-webrtc-streamer

# TODO: Instead of waiting for 1 second this should wait for the database to be migrated
echo ""
echo "Migrating database..."
sleep 1s

# Generate an invite key for the user
if [ $FRESH_INSTALL = "1" ]; then
  sudo teg-invite
fi
