#!/bin/bash
set -e
cd "$( dirname "${BASH_SOURCE[0]}" )" && cd ../

echo ""
echo "PrintSpool Release Preview"
echo "---------------------------------------------------------------------------------------------"

npx --no-install standard-version -a --dry-run

echo ""
echo ""
echo "Are you sure you want to release this new version of PrintSpool?"
echo "---------------------------------------------------------------------------------------------"
echo ""
select yn in "Yes" "No"; do
    case $yn in
        Yes ) break;;
        No ) exit 1;;
    esac
done

echo ""
echo "🎉 Yay! It's Release Day! 🎉"
echo ""

npx --no-install standard-version -a

echo "Publishing tags to Github..."
git push --follow-tags origin main
echo "Publishing tags to Github... [DONE]"

echo ""
echo "🎉 Congratulations! You did it! 🎉"
echo ""
