#!/bin/sh
set -e
# cd "$( dirname "${BASH_SOURCE[0]}" )" && cd ../

tmux start-server

if ! command -v mold &> /dev/null
then
  tmux new-session -s "teg" -n "server" -d \
    '$SHELL --rcfile <(echo ". ~/.bashrc; cd ./crates/ && history -s \"cargo watch -s \\\"mold -run \$cg_clif_dir/build/cargo-clif run\\\"\" && cargo watch -s \"mold -run \$cg_clif_dir/build/cargo-clif run\"")'
else
  tmux new-session -s "teg" -n "server" -d \
    '$SHELL --rcfile <(echo ". ~/.bashrc; cd ./crates/ && history -s \"cargo watch -x run\" && cargo watch -x run")'
fi
tmux new-window -n "web-ui" \
  '$SHELL --rcfile <(echo ". ~/.bashrc; cd ./frontend/teg-web-ui/ && nvm use && history -s \"yarn start\" && yarn start")'

tmux -2 attach-session -d
