#!/bin/sh
set -e
# cd "$( dirname "${BASH_SOURCE[0]}" )" && cd ../

tmux start-server

tmux new-session -s "teg" -n "server" -d \
  '$SHELL --rcfile <(echo ". ~/.bashrc; cd ./crates/ && history -s \"cargo watch -x run\" && cargo watch -x run")'
tmux new-window -n "web-ui" \
  '$SHELL --rcfile <(echo ". ~/.bashrc; cd ./packages/teg-web-ui/ && nvm use && history -s \"yarn start\" && yarn start")'

tmux -2 attach-session -d
